// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
let _VERSION = '0.0.0'; // This value will be overwritten by webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;
export const AUTH0_CLIENT_ID = 'cg8JQ1ubaI0vX1P2kZoIO5a11DloD5EW';
export const AUTH0_DOMAIN = 'oc4.auth0.com';
export const AUTH0_LOGIN_URL = 'skeleton.openclinica.info/auth';
